// Generated by gencpp from file auto_navi/try1.msg
// DO NOT EDIT!


#ifndef AUTO_NAVI_MESSAGE_TRY1_H
#define AUTO_NAVI_MESSAGE_TRY1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_navi
{
template <class ContainerAllocator>
struct try1_
{
  typedef try1_<ContainerAllocator> Type;

  try1_()
    : cX(0.0)
    , cY(0.0)  {
    }
  try1_(const ContainerAllocator& _alloc)
    : cX(0.0)
    , cY(0.0)  {
  (void)_alloc;
    }



   typedef double _cX_type;
  _cX_type cX;

   typedef double _cY_type;
  _cY_type cY;





  typedef boost::shared_ptr< ::auto_navi::try1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_navi::try1_<ContainerAllocator> const> ConstPtr;

}; // struct try1_

typedef ::auto_navi::try1_<std::allocator<void> > try1;

typedef boost::shared_ptr< ::auto_navi::try1 > try1Ptr;
typedef boost::shared_ptr< ::auto_navi::try1 const> try1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_navi::try1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_navi::try1_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_navi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'auto_navi': ['/home/hit_ter/rover_ws/src/auto_navi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_navi::try1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_navi::try1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_navi::try1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_navi::try1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_navi::try1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_navi::try1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_navi::try1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd466dd2a275f04fea16b85b9a5cea50";
  }

  static const char* value(const ::auto_navi::try1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd466dd2a275f04fULL;
  static const uint64_t static_value2 = 0xea16b85b9a5cea50ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_navi::try1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_navi/try1";
  }

  static const char* value(const ::auto_navi::try1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_navi::try1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 cX\n\
float64 cY\n\
";
  }

  static const char* value(const ::auto_navi::try1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_navi::try1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cX);
      stream.next(m.cY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct try1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_navi::try1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_navi::try1_<ContainerAllocator>& v)
  {
    s << indent << "cX: ";
    Printer<double>::stream(s, indent + "  ", v.cX);
    s << indent << "cY: ";
    Printer<double>::stream(s, indent + "  ", v.cY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_NAVI_MESSAGE_TRY1_H
