// Generated by gencpp from file auto_navi/try3.msg
// DO NOT EDIT!


#ifndef AUTO_NAVI_MESSAGE_TRY3_H
#define AUTO_NAVI_MESSAGE_TRY3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_navi
{
template <class ContainerAllocator>
struct try3_
{
  typedef try3_<ContainerAllocator> Type;

  try3_()
    : lat(0.0)
    , long(0.0)
    , X(0.0)
    , Y(0.0)  {
    }
  try3_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , long(0.0)
    , X(0.0)
    , Y(0.0)  {
  (void)_alloc;
    }



   typedef double _lat_type;
  _lat_type lat;

   typedef double _long_type;
  _long_type long;

   typedef double _X_type;
  _X_type X;

   typedef double _Y_type;
  _Y_type Y;





  typedef boost::shared_ptr< ::auto_navi::try3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_navi::try3_<ContainerAllocator> const> ConstPtr;

}; // struct try3_

typedef ::auto_navi::try3_<std::allocator<void> > try3;

typedef boost::shared_ptr< ::auto_navi::try3 > try3Ptr;
typedef boost::shared_ptr< ::auto_navi::try3 const> try3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_navi::try3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_navi::try3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_navi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'auto_navi': ['/home/hit_ter/rover_ws/src/auto_navi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_navi::try3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_navi::try3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_navi::try3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_navi::try3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_navi::try3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_navi::try3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_navi::try3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1aba966ad6a1f4a1f3e7976f86d20de";
  }

  static const char* value(const ::auto_navi::try3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1aba966ad6a1f4aULL;
  static const uint64_t static_value2 = 0x1f3e7976f86d20deULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_navi::try3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_navi/try3";
  }

  static const char* value(const ::auto_navi::try3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_navi::try3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lat\n\
float64 long\n\
float64 X\n\
float64 Y\n\
";
  }

  static const char* value(const ::auto_navi::try3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_navi::try3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.long);
      stream.next(m.X);
      stream.next(m.Y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct try3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_navi::try3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_navi::try3_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "long: ";
    Printer<double>::stream(s, indent + "  ", v.long);
    s << indent << "X: ";
    Printer<double>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<double>::stream(s, indent + "  ", v.Y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_NAVI_MESSAGE_TRY3_H
