(cl:defpackage katana_msgs-msg
  (:use )
  (:export
   "<GRIPPERCONTROLLERSTATE>"
   "GRIPPERCONTROLLERSTATE"
   "<JOINTMOVEMENTACTION>"
   "JOINTMOVEMENTACTION"
   "<JOINTMOVEMENTACTIONFEEDBACK>"
   "JOINTMOVEMENTACTIONFEEDBACK"
   "<JOINTMOVEMENTACTIONGOAL>"
   "JOINTMOVEMENTACTIONGOAL"
   "<JOINTMOVEMENTACTIONRESULT>"
   "JOINTMOVEMENTACTIONRESULT"
   "<JOINTMOVEMENTFEEDBACK>"
   "JOINTMOVEMENTFEEDBACK"
   "<JOINTMOVEMENTGOAL>"
   "JOINTMOVEMENTGOAL"
   "<JOINTMOVEMENTRESULT>"
   "JOINTMOVEMENTRESULT"
  ))

