// Generated by gencpp from file katana_msgs/GripperControllerState.msg
// DO NOT EDIT!


#ifndef KATANA_MSGS_MESSAGE_GRIPPERCONTROLLERSTATE_H
#define KATANA_MSGS_MESSAGE_GRIPPERCONTROLLERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace katana_msgs
{
template <class ContainerAllocator>
struct GripperControllerState_
{
  typedef GripperControllerState_<ContainerAllocator> Type;

  GripperControllerState_()
    : header()
    , name()
    , actual()
    , desired()
    , error()  {
    }
  GripperControllerState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , actual(_alloc)
    , desired(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actual_type;
  _actual_type actual;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _desired_type;
  _desired_type desired;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::katana_msgs::GripperControllerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::katana_msgs::GripperControllerState_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControllerState_

typedef ::katana_msgs::GripperControllerState_<std::allocator<void> > GripperControllerState;

typedef boost::shared_ptr< ::katana_msgs::GripperControllerState > GripperControllerStatePtr;
typedef boost::shared_ptr< ::katana_msgs::GripperControllerState const> GripperControllerStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::katana_msgs::GripperControllerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::katana_msgs::GripperControllerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace katana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'katana_msgs': ['/home/hit_ter/rover_ws/src/katana_driver/katana_msgs/msg', '/home/hit_ter/rover_ws/devel/share/katana_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::katana_msgs::GripperControllerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::katana_msgs::GripperControllerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::katana_msgs::GripperControllerState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57ba9ed166f48062eddf3c6e509f2dc0";
  }

  static const char* value(const ::katana_msgs::GripperControllerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57ba9ed166f48062ULL;
  static const uint64_t static_value2 = 0xeddf3c6e509f2dc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "katana_msgs/GripperControllerState";
  }

  static const char* value(const ::katana_msgs::GripperControllerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The actual and desired angles (in radian) of the gripper joints, \n\
# and the error between actual and desired.\n\
#\n\
# Each joint is uniquely identified by its name.\n\
#\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
#\n\
# All arrays in this message should have the same size.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
Header header\n\
\n\
string[] name\n\
float64[] actual\n\
float64[] desired\n\
float64[] error\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::katana_msgs::GripperControllerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.actual);
      stream.next(m.desired);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControllerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::katana_msgs::GripperControllerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::katana_msgs::GripperControllerState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "actual[]" << std::endl;
    for (size_t i = 0; i < v.actual.size(); ++i)
    {
      s << indent << "  actual[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actual[i]);
    }
    s << indent << "desired[]" << std::endl;
    for (size_t i = 0; i < v.desired.size(); ++i)
    {
      s << indent << "  desired[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.desired[i]);
    }
    s << indent << "error[]" << std::endl;
    for (size_t i = 0; i < v.error.size(); ++i)
    {
      s << indent << "  error[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.error[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KATANA_MSGS_MESSAGE_GRIPPERCONTROLLERSTATE_H
